import random

SUGGESTION_WORDS = [
    "PINEAPPLE",
    "ELEVATOR",
    "ASTRONAUT",
    "SUBMARINE",
    "UMBRELLA",
    "VOLCANO",
    "NOTEBOOK",
    "TELESCOPE",
    "MARSHMALLOW",
    "DINOSAUR",
    "HEADPHONES",
    "BACKPACK",
    "LIBRARY",
    "RAINSTORM",
    "BICYCLE",
    "PARACHUTE",
    "SANDWICH",
    "HOTEL",
    "JELLYFISH",
    "CAMERA",
    "TOOTHBRUSH",
    "BANANA",
    "MAGNET",
    "DRAGON",
    "HOSPITAL",
    "CARNIVAL",
    "SAILBOAT",
    "MICROSCOPE",
    "KEYBOARD",
    "ROLLERCOASTER",
    "SNOWFLAKE",
    "FIREPLACE",
    "ROBOT",
    "PAINTBRUSH",
    "GUITAR",
    "MOONLIGHT",
    "SHADOW",
    "COCONUT",
    "ICEBERG",
    "TREASURE",
    "SPACESHIP",
    "PUPPET",
    "BUBBLE",
    "LANTERN",
    "CANYON",
    "ZEBRA",
    "ORANGE",
    "MARKET",
    "TUNNEL"
]


def get_suggestion() -> str:
    return random.choice(SUGGESTION_WORDS)
